const actionTypes = {
  LEFTNAV: {
    ADD_MENU: "LEFTNAV-ADD_MENU",
    REMOVE_MENU: "LEFTNAV-REMOVE_MENU",
    TOGGLE_MENU: "LEFTNAV-TOGGLE_MENU"
  },
  FOLDER: {
    TOGGLE_FOLDER: "FOLDER-TOGGLE_FOLDER",
    RENAME_FOLDER: "FOLDER-RENAME_FOLDER",
    UPDATE_FOLDER_CONTENTS: "FOLDER-UPDATE_FOLDER_CONTENT"
  },
  FILE: {
    TOGGLE_FILE: "FILE-TOGGLE_FILE",
    RENAME_FILE: "FILE-RENAME_FILE"
  }
};

export default actionTypes;
