const actionTypes = {
  LEFTNAV: {
    ADD_CONTENT: "LEFTNAV-ADD_CONTENT",
    REMOVE_CONTENT: "LEFTNAV-REMOVE_CONTENT",
    TOGGLE_MENU: "LEFTNAV-TOGGLE_MENU",
    RENAME_CONTENT: "LEFTNAV-RENAME_CONTENT"
  }
};

export default actionTypes;
